# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: مقاله‌های دوست‌داشتنیِ علوم‌شناختی
email: ansarinia@me.com
description: > # this means to ignore newlines until "baseurl:"
  Cognitive Science Papers We Like, inspired by *Papers We Love* Project
  lists interesting papers and publications in Cognitive Science fields.
  It is currently available at http://cog.onto.ir.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cog.onto.ir" # the base hostname & protocol for your site
timezone: Asia/Tehran
encoding: utf-8
twitter_username:
github_username:  morteza

# Build settings
markdown: kramdown
theme: minima
